# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    cohort_code_use = FALSE,
    summarise_cohort_overlap = FALSE,
    summarise_cohort_count = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_cohort_timing = FALSE,
    summarise_characteristics = FALSE,
    summarise_large_scale_characteristics = FALSE,
    survival = FALSE,
    summarise_log_file = FALSE
  )


  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_omop_snapshot_cdm_name,
      input$summarise_omop_snapshot_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot(
        header = input$summarise_omop_snapshot_table_header,
        groupColumn = input$summarise_omop_snapshot_table_group_column,
        hide = input$summarise_omop_snapshot_table_hide
      )
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_observation_period <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_observation_period_cdm_name,
      input$summarise_observation_period_observation_period_ordinal,
      input$summarise_observation_period_variable_name,
      input$summarise_observation_period_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_observation_period <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })

  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal)
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod(
        header = input$summarise_observation_period_table_header,
        groupColumn = input$summarise_observation_period_table_group_column,
        hide = input$summarise_observation_period_table_hide
      )
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )

  # cohort_code_use -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cohort_code_use <- TRUE
  }) |>
    shiny::bindEvent(
      input$cohort_code_use_cdm_name,
      input$cohort_code_use_cohort_name,
      input$cohort_code_use_codelist_name,
      input$cohort_code_use_variable_name,
      input$cohort_code_use_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cohort_code_use, {
    if (updateButtons$cohort_code_use == TRUE) {
      output$update_message_cohort_code_use <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_cohort_code_use <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cohort_code_use, {
    updateButtons$cohort_code_use <- FALSE
  })

  ## get cohort_code_use data
  getCohortCodeUseData <- shiny::eventReactive(input$update_cohort_code_use, {
    data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name,
        .data$variable_name %in% input$cohort_code_use_variable_name,
        .data$estimate_name %in% input$cohort_code_use_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$cohort_name %in% input$cohort_code_use_cohort_name,
        .data$codelist_name %in% input$cohort_code_use_codelist_name
      )
  })
  getCohortCodeUseTableReact <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        type = "reactable",
        header = "cdm_name"
      )
  })
  output$cohort_code_use_table_react <- reactable::renderReactable({
    getCohortCodeUseTableReact()
  })
  getCohortCodeUseTableGt <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        timing = TRUE,
        header = input$cohort_code_use_table_gt_header,
        groupColumn = input$cohort_code_use_table_gt_group_column,
        hide = input$cohort_code_use_table_gt_hide
      )
  })
  output$cohort_code_use_table_gt <- gt::render_gt({
    getCohortCodeUseTableGt()
  })
  output$cohort_code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_code_use.", input$cohort_code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getCohortCodeUseTableGt(), file)
    }
  )

  # summarise_cohort_overlap -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_overlap <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_overlap_cdm_name,
      input$summarise_cohort_overlap_cohort_name_reference,
      input$summarise_cohort_overlap_cohort_name_comparator,
      input$summarise_cohort_overlap_variable_name,
      input$summarise_cohort_overlap_estimate_name,
      input$summarise_cohort_overlap_overlap_by,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_overlap, {
    if (updateButtons$summarise_cohort_overlap == TRUE) {
      output$update_message_summarise_cohort_overlap <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_overlap <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_overlap, {
    updateButtons$summarise_cohort_overlap <- FALSE
  })

  ## get summarise_cohort_overlap data
  getSummariseCohortOverlapData <- shiny::eventReactive(input$update_summarise_cohort_overlap, {
    data[["summarise_cohort_overlap"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_overlap_cdm_name,
        .data$variable_name %in% input$summarise_cohort_overlap_variable_name,
        .data$estimate_name %in% input$summarise_cohort_overlap_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$cohort_name_reference %in% input$summarise_cohort_overlap_cohort_name_reference,
        .data$cohort_name_comparator %in% input$summarise_cohort_overlap_cohort_name_comparator
      ) |>
      omopgenerics::filterSettings(.data$overlap_by %in% input$summarise_cohort_overlap_overlap_by)
  })
  getSummariseCohortOverlapTable <- shiny::reactive({
    getSummariseCohortOverlapData() |>
      CohortCharacteristics::tableCohortOverlap(
        uniqueCombinations = input$summarise_cohort_overlap_table_unique_combinations,
        header = input$summarise_cohort_overlap_table_header,
        groupColumn = input$summarise_cohort_overlap_table_group_column,
        hide = input$summarise_cohort_overlap_table_hide
      )
  })
  output$summarise_cohort_overlap_table <- gt::render_gt({
    getSummariseCohortOverlapTable()
  })
  output$summarise_cohort_overlap_table_download <- shiny::downloadHandler(
    filename = paste0("table_overlap.", input$summarise_cohort_overlap_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortOverlapTable(), file)
    }
  )
  getSummariseCohortOverlapPlot <- shiny::reactive({
    getSummariseCohortOverlapData() |>
      CohortCharacteristics::plotCohortOverlap(
        facet = input$summarise_cohort_overlap_plot_facet
      )
  })
  output$summarise_cohort_overlap_plot <- shiny::renderUI({
    x <- getSummariseCohortOverlapPlot()
    renderInteractivePlot(x, input$summarise_cohort_overlap_plot_interactive)
  })
  output$summarise_cohort_overlap_plot_download <- shiny::downloadHandler(
    filename = "plot_overlap.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortOverlapPlot(),
        width = as.numeric(input$summarise_cohort_overlap_plot_width),
        height = as.numeric(input$summarise_cohort_overlap_plot_height),
        units = input$summarise_cohort_overlap_plot_units,
        dpi = as.numeric(input$summarise_cohort_overlap_plot_dpi)
      )
    }
  )

  # summarise_cohort_count -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_count <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_count_cdm_name,
      input$summarise_cohort_count_cohort_name,
      input$summarise_cohort_count_aortic_valve_repair,
      input$summarise_cohort_count_surgical_valvotomy,
      input$summarise_cohort_count_percutaneous_valvotomy,
      input$summarise_cohort_count_ross_procedure,
      input$summarise_cohort_count_aortic_valve_replacement,
      input$summarise_cohort_count_variable_name,
      input$summarise_cohort_count_table_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_count, {
    if (updateButtons$summarise_cohort_count == TRUE) {
      output$update_message_summarise_cohort_count <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_count <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_count, {
    updateButtons$summarise_cohort_count <- FALSE
  })

  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::eventReactive(input$update_summarise_cohort_count, {
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_count_cohort_name) |>
      omopgenerics::filterStrata(
        .data$aortic_valve_repair %in% input$summarise_cohort_count_aortic_valve_repair,
        .data$surgical_valvotomy %in% input$summarise_cohort_count_surgical_valvotomy,
        .data$percutaneous_valvotomy %in% input$summarise_cohort_count_percutaneous_valvotomy,
        .data$ross_procedure %in% input$summarise_cohort_count_ross_procedure,
        .data$aortic_valve_replacement %in% input$summarise_cohort_count_aortic_valve_replacement
      ) |>
      omopgenerics::filterSettings(.data$table_name %in% input$summarise_cohort_count_table_name)
  })
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )

  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_attrition_cdm_name,
      input$summarise_cohort_attrition_cohort_name,
      input$summarise_cohort_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })

  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )

  # summarise_cohort_timing -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_timing <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_timing_cdm_name,
      input$summarise_cohort_timing_cohort_name_reference,
      input$summarise_cohort_timing_cohort_name_comparator,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_timing, {
    if (updateButtons$summarise_cohort_timing == TRUE) {
      output$update_message_summarise_cohort_timing <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_timing <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_timing, {
    updateButtons$summarise_cohort_timing <- FALSE
  })

  ## get summarise_cohort_timing data
  getSummariseCohortTimingData <- shiny::eventReactive(input$update_summarise_cohort_timing, {
    data[["summarise_cohort_timing"]] |>
      dplyr::filter(.data$cdm_name %in% input$summarise_cohort_timing_cdm_name) |>
      omopgenerics::filterGroup(
        .data$cohort_name_reference %in% input$summarise_cohort_timing_cohort_name_reference,
        .data$cohort_name_comparator %in% input$summarise_cohort_timing_cohort_name_comparator
      )
  })
  getSummariseCohortTimingTable <- shiny::reactive({
    getSummariseCohortTimingData() |>
      CohortCharacteristics::tableCohortTiming(
        timeScale = input$summarise_cohort_timing_table_time_scale,
        header = input$summarise_cohort_timing_table_header,
        groupColumn = input$summarise_cohort_timing_table_group_column,
        hide = input$summarise_cohort_timing_table_hide
      )
  })
  output$summarise_cohort_timing_table <- gt::render_gt({
    getSummariseCohortTimingTable()
  })
  output$summarise_cohort_timing_table_download <- shiny::downloadHandler(
    filename = paste0("table_timing.", input$summarise_cohort_timing_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortTimingTable(), file)
    }
  )
  getSummariseCohortTimingPlot <- shiny::reactive({
    getSummariseCohortTimingData() |>
      CohortCharacteristics::plotCohortTiming(
        plotType = input$summarise_cohort_timing_plot_plot_type,
        timeScale = input$summarise_cohort_timing_plot_time_scale,
        uniqueCombinations = input$summarise_cohort_timing_plot_unique_combinations,
        facet = input$summarise_cohort_timing_plot_facet,
        colour = input$summarise_cohort_timing_plot_colour
      )
  })
  output$summarise_cohort_timing_plot <- shiny::renderUI({
    x <- getSummariseCohortTimingPlot()
    renderInteractivePlot(x, input$summarise_cohort_timing_plot_interactive)
  })
  output$summarise_cohort_timing_plot_download <- shiny::downloadHandler(
    filename = "plot_timing.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortTimingPlot(),
        width = as.numeric(input$summarise_cohort_timing_plot_width),
        height = as.numeric(input$summarise_cohort_timing_plot_height),
        units = input$summarise_cohort_timing_plot_units,
        dpi = as.numeric(input$summarise_cohort_timing_plot_dpi)
      )
    }
  )

  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_characteristics_cdm_name,
      input$summarise_characteristics_cohort_name,
      input$summarise_characteristics_age_group,
      input$summarise_characteristics_sex,
      input$summarise_characteristics_variable_name,
      input$summarise_characteristics_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_characteristics_age_group,
        .data$sex %in% input$summarise_characteristics_sex
      )
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )

  # summarise_large_scale_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_large_scale_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_large_scale_characteristics_cdm_name,
      input$summarise_large_scale_characteristics_cohort_name,
      input$summarise_large_scale_characteristics_variable_level,
      input$summarise_large_scale_characteristics_analysis,
      input$summarise_large_scale_characteristics_table_name,
      input$summarise_large_scale_characteristics_type,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_large_scale_characteristics, {
    if (updateButtons$summarise_large_scale_characteristics == TRUE) {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_large_scale_characteristics, {
    updateButtons$summarise_large_scale_characteristics <- FALSE
  })

  ## get summarise_large_scale_characteristics data
  getSummariseLargeScaleCharacteristicsData <- shiny::eventReactive(input$update_summarise_large_scale_characteristics, {
    data[["summarise_large_scale_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_large_scale_characteristics_cdm_name,
        .data$variable_level %in% input$summarise_large_scale_characteristics_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_large_scale_characteristics_cohort_name) |>
      omopgenerics::filterSettings(
        .data$analysis %in% input$summarise_large_scale_characteristics_analysis,
        .data$table_name %in% input$summarise_large_scale_characteristics_table_name,
        .data$type %in% input$summarise_large_scale_characteristics_type
      )
  })
  getSummariseLargeScaleCharacteristicsTableLsc <- shiny::reactive({
    if (identical(input$summarise_large_scale_characteristics_table_lsc_compare_by, "no compare")) {
      cb <- NULL
    } else {
      cb <- input$summarise_large_scale_characteristics_table_lsc_compare_by
    }
    if (identical(input$summarise_large_scale_characteristics_table_lsc_smd_reference, "no SMD")) {
      sr <- NULL
    } else {
      sr <- input$summarise_large_scale_characteristics_table_lsc_smd_reference
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableLargeScaleCharacteristics(
        compareBy = cb,
        hide = input$summarise_large_scale_characteristics_table_lsc_hide,
        smdReference = sr
      )
  })
  output$summarise_large_scale_characteristics_table_lsc <- reactable::renderReactable({
    getSummariseLargeScaleCharacteristicsTableLsc()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_table_lsc_compare_by, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_table_lsc_compare_by)]]
    opts <- c("no SMD", opts)
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_table_lsc_smd_reference",
      choices = opts,
      selected = "no SMD"
    )
  })
  output$summarise_large_scale_characteristics_table_lsc_download <- shiny::downloadHandler(
    filename = "smd_results.csv",
    content = function(file) {
      rt <- getSummariseLargeScaleCharacteristicsTableLsc()
      rt$x$tag$attribs$data |>
        unclass() |>
        jsonlite::fromJSON() |>
        dplyr::as_tibble() |>
        readr::write_csv(file)
    }
  )
  getSummariseLargeScaleCharacteristicsTableMostCommon <- shiny::reactive({
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableTopLargeScaleCharacteristics(
        topConcepts = input$summarise_large_scale_characteristics_table_most_common_top_concepts,
        type = "gt"
      )
  })
  output$summarise_large_scale_characteristics_table_most_common <- gt::render_gt({
    getSummariseLargeScaleCharacteristicsTableMostCommon()
  })
  output$summarise_large_scale_characteristics_table_most_common_download <- shiny::downloadHandler(
    filename = paste0("top_concepts.", input$summarise_large_scale_characteristics_table_most_common_format),
    content = function(file) {
      gt::gtsave(getSummariseLargeScaleCharacteristicsTableMostCommon(), file)
    }
  )
  getSummariseLargeScaleCharacteristicsPlotCompared <- shiny::reactive({
    if (input$summarise_large_scale_characteristics_plot_compared_missings) {
      mis <- 0
    } else {
      mis <- NULL
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::plotComparedLargeScaleCharacteristics(
        colour = input$summarise_large_scale_characteristics_plot_compared_colour,
        reference = input$summarise_large_scale_characteristics_plot_compared_reference,
        facet = input$summarise_large_scale_characteristics_plot_compared_facet,
        missings = mis
      )
  })
  output$summarise_large_scale_characteristics_plot_compared <- plotly::renderPlotly({
    getSummariseLargeScaleCharacteristicsPlotCompared()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_plot_compared_colour, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_plot_compared_colour)]]
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_plot_compared_reference",
      choices = opts,
      selected = opts[1]
    )
  })

  # survival -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$survival <- TRUE
  }) |>
    shiny::bindEvent(
      input$survival_cdm_name,
      input$survival_target_cohort,
      input$survival_age_group,
      input$survival_sex,
      input$survival_reason,
      input$survival_variable_level,
      input$survival_analysis_type,
      input$survival_censor_on_cohort_exit,
      input$survival_competing_outcome,
      input$survival_follow_up_days,
      input$survival_minimum_survival_days,
      input$survival_outcome,
      input$survival_outcome_date_variable,
      input$survival_outcome_washout,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$survival, {
    if (updateButtons$survival == TRUE) {
      output$update_message_survival <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_survival <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_survival, {
    updateButtons$survival <- FALSE
  })

  ## get survival data
  getSurvivalData <- shiny::eventReactive(input$update_survival, {
    data[["survival"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$survival_cdm_name,
        .data$variable_level %in% input$survival_variable_level
      ) |>
      omopgenerics::filterGroup(.data$target_cohort %in% input$survival_target_cohort) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$survival_age_group,
        .data$sex %in% input$survival_sex,
        .data$reason %in% input$survival_reason
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_type %in% input$survival_analysis_type,
        .data$censor_on_cohort_exit %in% input$survival_censor_on_cohort_exit,
        .data$competing_outcome %in% input$survival_competing_outcome,
        .data$follow_up_days %in% input$survival_follow_up_days,
        .data$minimum_survival_days %in% input$survival_minimum_survival_days,
        .data$outcome %in% input$survival_outcome,
        .data$outcome_date_variable %in% input$survival_outcome_date_variable,
        .data$outcome_washout %in% input$survival_outcome_washout
      )
  })
  getSurvivalTableSurvival <- shiny::reactive({
    getSurvivalData() |>
      CohortSurvival::tableSurvival(
        timeScale = input$survival_table_survival_time_scale,
        type = "gt"
      )
  })
  output$survival_table_survival <- gt::render_gt({
    getSurvivalTableSurvival()
  })
  output$survival_table_survival_download <- shiny::downloadHandler(
    filename = paste0("table_survival_summary.", input$survival_table_survival_format),
    content = function(file) {
      gt::gtsave(getSurvivalTableSurvival(), file)
    }
  )
  getSurvivalTableEvents <- shiny::reactive({
    getSurvivalData() |>
      CohortSurvival::tableSurvivalEvents(
        type = "gt"
      )
  })
  output$survival_table_events <- gt::render_gt({
    getSurvivalTableEvents()
  })
  output$survival_table_events_download <- shiny::downloadHandler(
    filename = paste0("table_survival_events.", input$survival_table_events_format),
    content = function(file) {
      gt::gtsave(getSurvivalTableEvents(), file)
    }
  )
  getSurvivalTableAttrition <- shiny::reactive({
    getSurvivalData() |>
      CohortSurvival::tableSurvivalAttrition(
        type = "gt"
      )
  })
  output$survival_table_attrition <- gt::render_gt({
    getSurvivalTableAttrition()
  })
  output$survival_table_attrition_download <- shiny::downloadHandler(
    filename = paste0("table_survival_attrition.", input$survival_table_attrition_format),
    content = function(file) {
      gt::gtsave(getSurvivalTableAttrition(), file)
    }
  )
  getSurvivalPlotSurvival <- shiny::reactive({
    getSurvivalData() |>
      CohortSurvival::plotSurvival(
        facet = input$survival_plot_survival_facet,
        colour = input$survival_plot_survival_colour,
        cumulativeFailure = input$survival_plot_survival_cumulative_failure,
        logLog = input$survival_plot_survival_log_log,
        timeScale = input$survival_plot_survival_time_scale
      )
  })
  output$survival_plot_survival <- shiny::renderUI({
    x <- getSurvivalPlotSurvival()
    renderInteractivePlot(x, input$survival_plot_survival_interactive)
  })
  output$survival_plot_survival_download <- shiny::downloadHandler(
    filename = "plot_survival.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSurvivalPlotSurvival(),
        width = as.numeric(input$survival_plot_survival_width),
        height = as.numeric(input$survival_plot_survival_height),
        units = input$survival_plot_survival_units,
        dpi = as.numeric(input$survival_plot_survival_dpi)
      )
    }
  )

  # summarise_log_file -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_log_file <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_log_file_cdm_name,
      input$summarise_log_file_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_log_file, {
    if (updateButtons$summarise_log_file == TRUE) {
      output$update_message_summarise_log_file <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_log_file <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_log_file, {
    updateButtons$summarise_log_file <- FALSE
  })

  ## get summarise_log_file data
  getSummariseLogFileData <- shiny::eventReactive(input$update_summarise_log_file, {
    data[["summarise_log_file"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_log_file_cdm_name,
        .data$variable_name %in% input$summarise_log_file_variable_name
      )
  })
  getSummariseLogFileTable <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "date_time") |>
      visOmopResults::visOmopTable(
        header = "cdm_name",
        hide = c("variable_level", "estimate_name")
      )
  })
  output$summarise_log_file_table <- gt::render_gt({
    getSummariseLogFileTable()
  })
  output$summarise_log_file_table_download <- shiny::downloadHandler(
    filename = paste0("table_log.", input$summarise_log_file_table_format),
    content = function(file) {
      gt::gtsave(getSummariseLogFileTable(), file)
    }
  )
  getSummariseLogFilePlot <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "elapsed_time") |>
      visOmopResults::barPlot(
        x = c("log_id", "variable_name"),
        y = "elapsed_time",
        colour = "cdm_name",
        position = input$summarise_log_file_plot_position
      )
  })
  output$summarise_log_file_plot <- shiny::renderUI({
    x <- getSummariseLogFilePlot()
    renderInteractivePlot(x, input$summarise_log_file_plot_interactive)
  })
  output$summarise_log_file_plot_download <- shiny::downloadHandler(
    filename = "plot_logs.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseLogFilePlot(),
        width = as.numeric(input$summarise_log_file_plot_width),
        height = as.numeric(input$summarise_log_file_plot_height),
        units = input$summarise_log_file_plot_units,
        dpi = as.numeric(input$summarise_log_file_plot_dpi)
      )
    }
  )
}
