# Generated by OmopViewer 0.7.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(brand = TRUE),
  shiny::tags$style(HTML(
    ".sticky-top-btn {
      position: sticky;
      top: 0;
      z-index: 20;
      background: var(--bs-body-bg);
    }"
  )),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    bslib::card(
      bslib::card_header("Explore results"),
      shiny::tags$div(
        class = "mb-2",
        shinyTree::shinyTree("summary_cdm_name", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_packages", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_min_cell_count", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_panels", theme = "proton", themeIcons = FALSE)
      ),
      full_screen = TRUE
    )
  ),
  bslib::nav_menu(
    title = "OmopSketch",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("camera"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_omop_snapshot",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_omop_snapshot")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_cdm_name",
            label = "CDM name",
            choices = choices$summarise_omop_snapshot_cdm_name,
            selected = selected$summarise_omop_snapshot_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_variable_name",
            label = "Variable name",
            choices = choices$summarise_omop_snapshot_variable_name,
            selected = selected$summarise_omop_snapshot_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Snapshot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "estimate_name",
                      input_id = "summarise_omop_snapshot_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cdm_name",
                      input_id = "summarise_omop_snapshot_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "variable_name",
                      input_id = "summarise_omop_snapshot_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "variable_level",
                      input_id = "summarise_omop_snapshot_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_omop_snapshot_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Observation period Summary",
      icon = shiny::icon("eye"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_observation_period",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_observation_period")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_cdm_name",
            label = "CDM name",
            choices = choices$summarise_observation_period_cdm_name,
            selected = selected$summarise_observation_period_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_observation_period_ordinal",
            label = "Observation period ordinal",
            choices = choices$summarise_observation_period_observation_period_ordinal,
            selected = selected$summarise_observation_period_observation_period_ordinal,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_variable_name",
            label = "Variable name",
            choices = choices$summarise_observation_period_variable_name,
            selected = selected$summarise_observation_period_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_observation_period_estimate_name,
            selected = selected$summarise_observation_period_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("observation_period_ordinal", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_observation_period_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cdm_name",
                      input_id = "summarise_observation_period_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_observation_period_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = character(),
                      input_id = "summarise_observation_period_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_observation_period_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_observation_period_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_variable",
                    label = "Variable",
                    choices = c("Number subjects", "Records per person", "Duration in days", "Days to next observation period"),
                    selected = "Number subjects",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "densityplot"),
                    selected = "barplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "observation_period_ordinal",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_observation_period_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "CodelistGenerator",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort code use",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_cohort_code_use",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_cohort_code_use")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cdm_name",
            label = "CDM name",
            choices = choices$cohort_code_use_cdm_name,
            selected = selected$cohort_code_use_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cohort_name",
            label = "Cohort name",
            choices = choices$cohort_code_use_cohort_name,
            selected = selected$cohort_code_use_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_codelist_name",
            label = "Codelist name",
            choices = choices$cohort_code_use_codelist_name,
            selected = selected$cohort_code_use_codelist_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_variable_name",
            label = "Variable name",
            choices = choices$cohort_code_use_variable_name,
            selected = selected$cohort_code_use_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_estimate_name",
            label = "Estimate name",
            choices = choices$cohort_code_use_estimate_name,
            selected = selected$cohort_code_use_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Cohort code use (reactable)",
            bslib::card(
              full_screen = TRUE,
              reactable::reactableOutput("cohort_code_use_table_react") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Table Cohort code use (gt)",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "cohort_code_use_table_gt_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "cohort_code_use_table_gt_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("cohort_name", "codelist_name", "source_concept_name", "source_concept_id", "source_concept_value", "type_concept_id", "type_concept_name", "domain_id", "table", "variable_name", "variable_level"),
                      input_id = "cohort_code_use_table_gt_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "estimate_name"),
                      input_id = "cohort_code_use_table_gt_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "cohort_code_use_table_gt_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = character(),
                      input_id = "cohort_code_use_table_gt_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("cohort_code_use_table_gt") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "CohortCharacteristics",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort Overlap",
      icon = shiny::icon("circle-half-stroke"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_cohort_overlap",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_cohort_overlap")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_overlap_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_overlap_cdm_name,
            selected = selected$summarise_cohort_overlap_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_overlap_cohort_name_reference",
            label = "Cohort name reference",
            choices = choices$summarise_cohort_overlap_cohort_name_reference,
            selected = selected$summarise_cohort_overlap_cohort_name_reference,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_overlap_cohort_name_comparator",
            label = "Cohort name comparator",
            choices = choices$summarise_cohort_overlap_cohort_name_comparator,
            selected = selected$summarise_cohort_overlap_cohort_name_comparator,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_overlap_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_overlap_variable_name,
            selected = selected$summarise_cohort_overlap_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_overlap_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_cohort_overlap_estimate_name,
            selected = selected$summarise_cohort_overlap_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_overlap_overlap_by",
            label = "Overlap by",
            choices = choices$summarise_cohort_overlap_overlap_by,
            selected = selected$summarise_cohort_overlap_overlap_by,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Overlap",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_overlap_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_overlap_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("cohort_name_reference", "cohort_name_comparator", "estimate_name"),
                      input_id = "summarise_cohort_overlap_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "variable_name",
                      input_id = "summarise_cohort_overlap_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "cdm_name",
                      input_id = "summarise_cohort_overlap_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "overlap_by"),
                      input_id = "summarise_cohort_overlap_table_hide"
                    )
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_cohort_overlap_table_unique_combinations",
                    label = "Unique combinations",
                    value = TRUE
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_overlap_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Overlap",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_overlap_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_overlap_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_overlap_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_overlap_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_overlap_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_cohort_overlap_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_overlap_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name_reference", "cohort_name_comparator", "overlap_by"),
                    selected = c("cdm_name", "cohort_name_reference"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_cohort_overlap_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Count",
      icon = shiny::icon("users"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_cohort_count",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_cohort_count")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_count_cdm_name,
            selected = selected$summarise_cohort_count_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_cohort_count_cohort_name,
            selected = selected$summarise_cohort_count_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_aortic_valve_repair",
            label = "Aortic valve repair",
            choices = choices$summarise_cohort_count_aortic_valve_repair,
            selected = selected$summarise_cohort_count_aortic_valve_repair,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_surgical_valvotomy",
            label = "Surgical valvotomy",
            choices = choices$summarise_cohort_count_surgical_valvotomy,
            selected = selected$summarise_cohort_count_surgical_valvotomy,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_percutaneous_valvotomy",
            label = "Percutaneous valvotomy",
            choices = choices$summarise_cohort_count_percutaneous_valvotomy,
            selected = selected$summarise_cohort_count_percutaneous_valvotomy,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_ross_procedure",
            label = "Ross procedure",
            choices = choices$summarise_cohort_count_ross_procedure,
            selected = selected$summarise_cohort_count_ross_procedure,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_aortic_valve_replacement",
            label = "Aortic valve replacement",
            choices = choices$summarise_cohort_count_aortic_valve_replacement,
            selected = selected$summarise_cohort_count_aortic_valve_replacement,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_count_variable_name,
            selected = selected$summarise_cohort_count_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_table_name",
            label = "Table name",
            choices = choices$summarise_cohort_count_table_name,
            selected = selected$summarise_cohort_count_table_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("aortic_valve_repair", "surgical_valvotomy", "percutaneous_valvotomy", "ross_procedure", "aortic_valve_replacement", "variable_name", "estimate_name"),
                      input_id = "summarise_cohort_count_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cohort_name",
                      input_id = "summarise_cohort_count_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "cdm_name",
                      input_id = "summarise_cohort_count_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "table_name"),
                      input_id = "summarise_cohort_count_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_count_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_cohort_count_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "aortic_valve_repair", "surgical_valvotomy", "percutaneous_valvotomy", "ross_procedure", "aortic_valve_replacement", "table_name"),
                    selected = c("cdm_name", "aortic_valve_repair", "surgical_valvotomy", "percutaneous_valvotomy", "ross_procedure", "aortic_valve_replacement"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "aortic_valve_repair", "surgical_valvotomy", "percutaneous_valvotomy", "ross_procedure", "aortic_valve_replacement", "table_name"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_cohort_count_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_cohort_attrition",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_cohort_attrition")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_attrition_cdm_name,
            selected = selected$summarise_cohort_attrition_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_cohort_attrition_cohort_name,
            selected = selected$summarise_cohort_attrition_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_attrition_variable_name,
            selected = selected$summarise_cohort_attrition_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "reason",
                      input_id = "summarise_cohort_attrition_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "variable_name",
                      input_id = "summarise_cohort_attrition_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_cohort_attrition_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "reason_id", "estimate_name", "age_range", "cdm_version", "cohort_definition_id", "vocabulary_version"),
                      input_id = "summarise_cohort_attrition_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_attrition_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Diagram",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_diagram_width",
                    label = "Width (px)",
                    value = 2000
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_diagram_download", label = "Download Diagram")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_diagram_show",
                    label = "Show",
                    choices = c("subjects", "records"),
                    selected = c("subjects", "records"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                DiagrammeR::grVizOutput("summarise_cohort_attrition_diagram") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Timing",
      icon = shiny::icon("chart-simple"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_cohort_timing",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_cohort_timing")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_timing_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_timing_cdm_name,
            selected = selected$summarise_cohort_timing_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_timing_cohort_name_reference",
            label = "Cohort name reference",
            choices = choices$summarise_cohort_timing_cohort_name_reference,
            selected = selected$summarise_cohort_timing_cohort_name_reference,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_timing_cohort_name_comparator",
            label = "Cohort name comparator",
            choices = choices$summarise_cohort_timing_cohort_name_comparator,
            selected = selected$summarise_cohort_timing_cohort_name_comparator,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Timing",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_timing_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("cohort_name_reference", "cohort_name_comparator"),
                      input_id = "summarise_cohort_timing_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = character(),
                      input_id = "summarise_cohort_timing_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "cdm_name",
                      input_id = "summarise_cohort_timing_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "restrict_to_first_entry"),
                      input_id = "summarise_cohort_timing_table_hide"
                    )
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_table_time_scale",
                    label = "Time scale",
                    choices = c("days", "years"),
                    selected = "days",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_timing_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Timing",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_timing_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_timing_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_timing_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_timing_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_cohort_timing_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "densityplot"),
                    selected = "boxplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_plot_time_scale",
                    label = "Time scale",
                    choices = c("days", "years"),
                    selected = "days",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_cohort_timing_plot_unique_combinations",
                    label = "Unique combinations",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name_reference", "cohort_name_comparator"),
                    selected = c("cdm_name", "cohort_name_reference"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name_reference", "cohort_name_comparator"),
                    selected = "cohort_name_comparator",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_cohort_timing_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_characteristics",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_characteristics")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_characteristics_cdm_name,
            selected = selected$summarise_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_characteristics_cohort_name,
            selected = selected$summarise_characteristics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_age_group",
            label = "Age group",
            choices = choices$summarise_characteristics_age_group,
            selected = selected$summarise_characteristics_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_sex",
            label = "Sex",
            choices = choices$summarise_characteristics_sex,
            selected = selected$summarise_characteristics_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_variable_name",
            label = "Variable name",
            choices = choices$summarise_characteristics_variable_name,
            selected = selected$summarise_characteristics_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_characteristics_estimate_name,
            selected = selected$summarise_characteristics_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("age_group", "sex", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_characteristics_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_characteristics_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_characteristics_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "scatterplot"),
                    selected = "boxplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "age_group", "sex"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "age_group", "sex"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_characteristics_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Large Scale Characteristics",
      icon = shiny::icon("arrow-up-right-dots"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_large_scale_characteristics",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_large_scale_characteristics")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_large_scale_characteristics_cdm_name,
            selected = selected$summarise_large_scale_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_large_scale_characteristics_cohort_name,
            selected = selected$summarise_large_scale_characteristics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_variable_level",
            label = "Variable level",
            choices = choices$summarise_large_scale_characteristics_variable_level,
            selected = selected$summarise_large_scale_characteristics_variable_level,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_analysis",
            label = "Analysis",
            choices = choices$summarise_large_scale_characteristics_analysis,
            selected = selected$summarise_large_scale_characteristics_analysis,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_table_name",
            label = "Table name",
            choices = choices$summarise_large_scale_characteristics_table_name,
            selected = selected$summarise_large_scale_characteristics_table_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_type",
            label = "Type",
            choices = choices$summarise_large_scale_characteristics_type,
            selected = selected$summarise_large_scale_characteristics_type,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_table_lsc_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_compare_by",
                    label = "Compare by",
                    choices = c("no compare", "cdm_name", "cohort_name", "type", "variable_level"),
                    selected = "no compare",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_hide",
                    label = "Hide",
                    choices = c("cdm_name", "cohort_name", "type", "variable_level"),
                    selected = "type",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_smd_reference",
                    label = "SMD reference",
                    choices = "no SMD",
                    selected = "no SMD",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                reactable::reactableOutput("summarise_large_scale_characteristics_table_lsc") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Most common codes",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_most_common_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_table_most_common_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_most_common_top_concepts",
                    label = "Top concepts",
                    choices = c(10L, 25L, 100L),
                    selected = 10L,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_large_scale_characteristics_table_most_common") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Compared",
            bslib::card(
              full_screen = TRUE,
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shiny.fluent::Toggle.shinyInput(
                    label = "Missing data",
                    onText = "Interpolate 0",
                    offText = "Eliminate",
                    value = TRUE,
                    inputId = "summarise_large_scale_characteristics_plot_compared_missings"
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "type", "variable_level"),
                    selected = NULL,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_reference",
                    label = "Reference",
                    choices = NULL,
                    selected = NULL,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "type", "variable_level"),
                    selected = c("cdm_name", "cohort_name"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                plotly::plotlyOutput("summarise_large_scale_characteristics_plot_compared") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Survival Analyses",
    icon = shiny::icon("stairs"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_survival",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_survival")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_cdm_name",
          label = "CDM name",
          choices = choices$survival_cdm_name,
          selected = selected$survival_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_target_cohort",
          label = "Target cohort",
          choices = choices$survival_target_cohort,
          selected = selected$survival_target_cohort,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_age_group",
          label = "Age group",
          choices = choices$survival_age_group,
          selected = selected$survival_age_group,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_sex",
          label = "Sex",
          choices = choices$survival_sex,
          selected = selected$survival_sex,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_reason",
          label = "Reason",
          choices = choices$survival_reason,
          selected = selected$survival_reason,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_variable_level",
          label = "Variable level",
          choices = choices$survival_variable_level,
          selected = selected$survival_variable_level,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_analysis_type",
          label = "Analysis type",
          choices = choices$survival_analysis_type,
          selected = selected$survival_analysis_type,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_censor_on_cohort_exit",
          label = "Censor on cohort exit",
          choices = choices$survival_censor_on_cohort_exit,
          selected = selected$survival_censor_on_cohort_exit,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_competing_outcome",
          label = "Competing outcome",
          choices = choices$survival_competing_outcome,
          selected = selected$survival_competing_outcome,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_follow_up_days",
          label = "Follow up days",
          choices = choices$survival_follow_up_days,
          selected = selected$survival_follow_up_days,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_minimum_survival_days",
          label = "Minimum survival days",
          choices = choices$survival_minimum_survival_days,
          selected = selected$survival_minimum_survival_days,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_outcome",
          label = "Outcome",
          choices = choices$survival_outcome,
          selected = selected$survival_outcome,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_outcome_date_variable",
          label = "Outcome date variable",
          choices = choices$survival_outcome_date_variable,
          selected = selected$survival_outcome_date_variable,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_outcome_washout",
          label = "Outcome washout",
          choices = choices$survival_outcome_washout,
          selected = selected$survival_outcome_washout,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Summary",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "survival_table_survival_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "survival_table_survival_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "survival_table_survival_time_scale",
                  label = "Time Scale",
                  choices = c("days", "months", "years"),
                  selected = "days",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              gt::gt_output("survival_table_survival") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table Events",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "survival_table_events_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "survival_table_events_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("survival_table_events") |>
              shinycssloaders::withSpinner()
          )
        ),
        bslib::nav_panel(
          title = "Table Attrition",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "survival_table_attrition_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "survival_table_attrition_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("survival_table_attrition") |>
              shinycssloaders::withSpinner()
          )
        ),
        bslib::nav_panel(
          title = "Plot Survival",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "survival_plot_survival_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "survival_plot_survival_height",
                  label = "Height",
                  value = 15
                ),
                shinyWidgets::pickerInput(
                  inputId = "survival_plot_survival_units",
                  label = "Units",
                  choices = c("px", "cm", "inch"),
                  selected = "cm",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::numericInput(
                  inputId = "survival_plot_survival_dpi",
                  label = "DPI",
                  value = 300
                ),
                shiny::downloadButton(outputId = "survival_plot_survival_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "survival_plot_survival_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::materialSwitch(
                  inputId = "survival_plot_survival_cumulative_failure",
                  label = "Cumulative failure",
                  value = FALSE
                ),
                shinyWidgets::materialSwitch(
                  inputId = "survival_plot_survival_log_log",
                  label = "Log-Log plot",
                  value = FALSE
                ),
                shinyWidgets::pickerInput(
                  inputId = "survival_plot_survival_time_scale",
                  label = "Time Scale",
                  choices = c("days", "months", "years"),
                  selected = "days",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "survival_plot_survival_facet",
                  label = "Facet",
                  choices = c("cdm_name", "target_cohort", "age_group", "sex", "reason", "time", "reason_id", "analysis_type", "censor_on_cohort_exit", "competing_outcome", "eventgap", "follow_up_days", "minimum_survival_days", "outcome", "outcome_date_variable", "outcome_washout"),
                  selected = "cdm_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "survival_plot_survival_colour",
                  label = "Colour",
                  choices = c("cdm_name", "target_cohort", "age_group", "sex", "reason", "time", "reason_id", "analysis_type", "censor_on_cohort_exit", "competing_outcome", "eventgap", "follow_up_days", "minimum_survival_days", "outcome", "outcome_date_variable", "outcome_washout"),
                  selected = "target_cohort",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::uiOutput("survival_plot_survival") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Logs",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_log_file",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_log_file")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_cdm_name",
          label = "CDM name",
          choices = choices$summarise_log_file_cdm_name,
          selected = selected$summarise_log_file_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_variable_name",
          label = "Variable name",
          choices = choices$summarise_log_file_variable_name,
          selected = selected$summarise_log_file_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Logs",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_log_file_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_log_file_table") |>
              shinycssloaders::withSpinner()
          )
        ),
        bslib::nav_panel(
          title = "Plot Timing",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_height",
                  label = "Height",
                  value = 15
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_plot_units",
                  label = "Units",
                  choices = c("px", "cm", "inch"),
                  selected = "cm",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_dpi",
                  label = "DPI",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_log_file_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "summarise_log_file_plot_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_plot_position",
                  label = "Columns",
                  choices = c("dodge", "stack"),
                  selected = "stack",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::uiOutput("summarise_log_file_plot") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.7.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
